services:
    app:
        build:
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - '3000:3000'
        depends_on:
            - translate

    translate:
        image: libretranslate/libretranslate:latest
        ports:
            - '5000:5000'
        environment:
            - HTTP_PORT=5000
